[package]
name = "fs-recon"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { workspace = true }
fs-core = { path = "../fs-core" }
egui = "0.36.1"
cudarc = { version = "0.19.9", default-features = false, features = ["driver", "nvrtc", "std", "fallback-dynamic-loading", "cuda-12060"] }

[dev-dependencies]
metavision-sys = { path = "../metavision-sys" }
crossbeam-channel = { workspace = true }
