
MODEL_CONFIGS = [{'model_hash': '9c8818c2cbea55eca56c7b447df170da',
  'model_name': 'wan_video_text_encoder',
  'model_class': 'dfuse.models.wan_video_text_encoder.WanTextEncoder'},
 {'model_hash': 'ccc42284ea13e1ad04693284c7a09be6',
  'model_name': 'wan_video_vae',
  'model_class': 'dfuse.models.wan_video_vae.WanVideoVAE',
  'state_dict_converter': 'dfuse.utils.state_dict_converters.wan_video_vae.WanVideoVAEStateDictConverter'},
 {'model_hash': '8f91998a9a74a47e2a364be51ef65986',
  'model_name': 'dfuse',
  'model_class': 'dfuse.models.dfuse.DFuse',
  'state_dict_converter': 'dfuse.utils.state_dict_converters.dfuse.DFuseStateDictConverter',
  'extra_kwargs': {'patch_size': [1, 2, 2],
                   'in_dim': 16,
                   'dim': 1536,
                   'ffn_dim': 8960,
                   'freq_dim': 256,
                   'text_dim': 4096,
                   'out_dim': 16,
                   'num_heads': 12,
                   'num_layers': 30,
                   'eps': 1e-06,
                   'num_modalities': 1,
                   'modulation_type': None,
                   'enable_position_phase': False}},
 {'model_hash': 'e1de6c02cdac79f8b739f4d3698cd216',
  'model_name': 'wan_video_vae',
  'model_class': 'dfuse.models.wan_video_vae.WanVideoVAE38',
  'state_dict_converter': 'dfuse.utils.state_dict_converters.wan_video_vae.WanVideoVAEStateDictConverter'}]
