VRAM_MANAGEMENT_MODULE_MAPS = {'dfuse.models.wan_video_text_encoder.WanTextEncoder': {'torch.nn.Linear': 'dfuse.core.vram.layers.AutoWrappedLinear',
                                                            'torch.nn.Embedding': 'dfuse.core.vram.layers.AutoWrappedModule',
                                                            'dfuse.models.wan_video_text_encoder.T5RelativeEmbedding': 'dfuse.core.vram.layers.AutoWrappedModule',
                                                            'dfuse.models.wan_video_text_encoder.T5LayerNorm': 'dfuse.core.vram.layers.AutoWrappedModule'},
 'dfuse.models.wan_video_vae.WanVideoVAE': {'torch.nn.Linear': 'dfuse.core.vram.layers.AutoWrappedLinear',
                                                'torch.nn.Conv2d': 'dfuse.core.vram.layers.AutoWrappedModule',
                                                'dfuse.models.wan_video_vae.RMS_norm': 'dfuse.core.vram.layers.AutoWrappedModule',
                                                'dfuse.models.wan_video_vae.CausalConv3d': 'dfuse.core.vram.layers.AutoWrappedModule',
                                                'dfuse.models.wan_video_vae.Upsample': 'dfuse.core.vram.layers.AutoWrappedModule',
                                                'torch.nn.SiLU': 'dfuse.core.vram.layers.AutoWrappedModule',
                                                'torch.nn.Dropout': 'dfuse.core.vram.layers.AutoWrappedModule'},
 'dfuse.models.wan_video_vae.WanVideoVAE38': {'torch.nn.Linear': 'dfuse.core.vram.layers.AutoWrappedLinear',
                                                  'torch.nn.Conv2d': 'dfuse.core.vram.layers.AutoWrappedModule',
                                                  'dfuse.models.wan_video_vae.RMS_norm': 'dfuse.core.vram.layers.AutoWrappedModule',
                                                  'dfuse.models.wan_video_vae.CausalConv3d': 'dfuse.core.vram.layers.AutoWrappedModule',
                                                  'dfuse.models.wan_video_vae.Upsample': 'dfuse.core.vram.layers.AutoWrappedModule',
                                                  'torch.nn.SiLU': 'dfuse.core.vram.layers.AutoWrappedModule',
                                                  'torch.nn.Dropout': 'dfuse.core.vram.layers.AutoWrappedModule'}}
